version: '3'

services:
  elastic-search:
    image: elasticsearch:7.17.22
    container_name: products_elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data
      

volumes:
  esdata: